#!/bin/sh
set -x #echo on

# RUN ME ON THE RASPBERRY PI logged in as user pi, from the home dir

# enable ssh,  add your public key to authorized keys for passwordless login as user pi 
if [ ! -d ".ssh" ]; then
  mkdir -p .ssh
  echo '' > .ssh/authorized_keys
  chmod 700 .ssh; chmod 640 .ssh/authorized_keys
fi

if [ ! -d "sunflower" ]; then
  mkdir sunflower
fi

sudo apt-get -y install vim
sudo apt-get -y install arduino arduino-core

# setup nodejs
wget https://nodejs.org/download/release/latest-v6.x/node-v6.1.0-linux-armv7l.tar.gz
tar -xvf node-v6.1.0-linux-armv7l.tar.gz
rm -f node-v6.1.0-linux-armv7l.tar.gz
sudo cp -R node-v6.1.0-linux-armv7l/* /usr/local/
rm -Rf node-v6.1.0-linux-armv7l/
node -v
npm --version

sudo npm install -g grunt-cli coffee-script