#!/bin/sh

#
# This script is run from the project root directory in a bash shell on your development 
# machine with the pi connected to it's standard (okay, really more hardcoded due to 
# laziness) ip address of 192.168.2.1.
#
# Before running this script you will need to configure the pi to accept ssh connections 
# and add your ssh key to the /home/pi/.ssh/authorized_keys file.  You will also need to 
# configure a route from the pi to the internet. 
#
# This script really just uploads ./setupFiles/_setupPi and executes over ssh
# All of the real work is done there. If you are having problems with ssh or scp
# working / connecting to your pi but you're able to use the shell some other way
# or use ftp to the pi, you can upload the ./setupFiles/_setupPi to the /home/pi
# directory and execute it there. 

scp scripts/setupFiles/_setupPi* pi@192.168.2.1:/home/pi
ssh pi@192.168.2.1 "cd /home/pi && chmod +x ./_setupPi* && ./_setupPi"
grunt build deployPi

# post deploy tasks
ssh pi@192.168.2.1 "cd /home/pi && ./_setupPiPostDeploy

